import Foundation

// MARK: - HtmlReport+Document
//
// The page around the sections: the header with the report's facts, the style sheet, the
// script and the footer with the integrity fingerprint.

extension HtmlReport {

    /// The finished document around `mainBody`. Its charts are HTML and CSS, so the page
    /// loads no library.
    func buildDocument(
        outputURL: URL,
        mainBody: String,
        inputs: Inputs,
        profile: String,
        glance: Glance?
    ) -> String {
        let orgName = config.branding?.resolvedOrgName ?? ""
        let title = orgName.isEmpty ? "Jamf Reports" : orgName
        let titleEscaped = HtmlSectionFormatters.escapeHTML(title)
        let accentColor = (config.branding ?? BrandingConfig()).sanitizedAccentColor
        let verifyFilename = HtmlSectionFormatters.escapeHTML(outputURL.lastPathComponent)
        let placeholder = HTMLReportSHA256Placeholder
        let controls = !expandAll && mainBody.contains("<details")
        return """
        <!DOCTYPE html>
        <html lang="en" data-theme="light">
        <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="report-sha256" content="\(placeholder)">
        <title>\(titleEscaped) — Jamf Instance Report</title>
        \(buildCSS(accentColor: accentColor))
        </head>
        <body>
        <a class="skip-link" href="#main-content">Skip to main content</a>
        \(buildHeader(
            title: titleEscaped, facts: headerFacts(inputs, profile: profile),
            controls: controls))
        <main id="main-content">
        \(mainBody)
        </main>
        <footer>
          <p>Generated by Jamf Reports &middot;
            <a href="https://github.com/tonyyo11/jamf-reports-community"
            >tonyyo11/jamf-reports-community</a></p>
          <p class="verify-footer" style="margin-top:8px;font-size:11px;opacity:0.7">
            Source fingerprint: <code>\(placeholder)</code>
            &middot; verify with <code>shasum -a 256 \(verifyFilename)</code>
            (see <code>report-sha256</code> meta tag; replace the hash field with 64 zeros
            to reproduce)
          </p>
        </footer>
        \(buildScript())
        </body>
        </html>
        """
    }

    // MARK: Header

    /// The facts under the title, each only when the app has the value: profile, when the
    /// data was collected, the jamf-cli version, how many Macs, the template and the
    /// reporting week. A fact the app lacks is left out, never printed as a dash.
    func headerFacts(_ inputs: Inputs, profile: String) -> [(label: String, value: String)] {
        var facts: [(label: String, value: String)] = []
        if !profile.isEmpty { facts.append(("Profile", profile)) }
        let snapshotDates = inputs.sources.filter { $0.kind != "snapshots/summaries" }
            .compactMap(\.date)
        if let collected = snapshotDates.max() {
            facts.append(("Data collected", Self.mediumDateTime(collected)))
        }
        let recorded = inputs.summaries.last?.provenance?.jamfCLIVersion
        if let version = (jamfCLIVersion ?? recorded).flatMap(Self.versionNumber(in:)) {
            facts.append(("jamf-cli", version))
        }
        let macs = [inputs.computers.count, inputs.totalDevices,
                    inputs.summaries.last?.totalDevices ?? 0].first { $0 > 0 }
        if let macs { facts.append(("Macs", "\(macs)")) }
        if let templateName, !templateName.isEmpty { facts.append(("Template", templateName)) }
        if let current = inputs.summaries.last {
            let prior = FleetReportEmitter.priorSummary(inputs.summaries, lookbackDays: 7)
            facts.append(("Reporting week", prior.map { "\($0.date) to \(current.date)" }
                ?? "ending \(current.date)"))
        }
        return facts
    }

    /// The version number in `text` ("jamf-cli version 1.31.1 (abc)" gives "1.31.1"); the
    /// trimmed text itself when it holds no number, nil when it is blank.
    static func versionNumber(in text: String) -> String? {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        let pattern = #"\d+(?:\.\d+)+(?:[-+][A-Za-z0-9.]+)?"#
        if let range = trimmed.range(of: pattern, options: .regularExpression) {
            return String(trimmed[range])
        }
        return trimmed
    }

    private static func mediumDateTime(_ date: Date) -> String {
        let fmt = DateFormatter()
        fmt.dateStyle = .medium
        fmt.timeStyle = .short
        return fmt.string(from: date)
    }

    private func buildHeader(
        title: String, facts: [(label: String, value: String)], controls: Bool
    ) -> String {
        let f = HtmlSectionFormatters.self
        let factHTML = facts.map {
            "<span class=\"fact\">\(f.escapeHTML($0.label)): <strong>\(f.escapeHTML($0.value))"
                + "</strong></span>"
        }.joined(separator: "\n      ")
        let buttons = controls ? """
              <div class="controls" role="group" aria-label="Section controls">
                <button type="button" class="ctl" data-action="expand">Expand all</button>
                <button type="button" class="ctl" data-action="collapse">Collapse all</button>
              </div>
        """ : ""
        return """
        <header>
          <div class="header-content">
            <div>
              <h1>\(title)</h1>
              <p class="subtitle">Jamf Instance Report · \(f.escapeHTML(formattedNow()))</p>
              <p class="header-facts">
              \(factHTML)
              </p>
            </div>
            <div class="header-actions">
        \(buttons)
              <button class="theme-toggle" onclick="toggleTheme()" aria-label="Toggle theme"
                aria-pressed="false">&#9728; / &#9790;</button>
            </div>
          </div>
        </header>
        """
    }

    // MARK: CSS

    func buildCSS(accentColor: String) -> String {
        """
        <style>
        /* Light mode is the default; dark mode is opt-in via data-theme="dark". */
        :root {
          --accent: \(accentColor);
          --bg: #f5f7fa;
          --bg2: #ffffff;
          --card: #ffffff;
          --text: #1a1a2e;
          --subtext: #555;
          --border: #dde;
          --green: #2e7d32;
          --yellow: #e65100;
          --red: #c62828;
        }
        [data-theme="dark"] {
          --bg: #1a1a2e;
          --bg2: #16213e;
          --card: #0f3460;
          --text: #e0e0e0;
          --subtext: #a0a0b0;
          --border: #2a3a5e;
          --green: #4caf50;
          --yellow: #ff9800;
          --red: #f44336;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
               background: var(--bg); color: var(--text); line-height: 1.5; }
        header { background: var(--bg2); border-bottom: 1px solid var(--border);
                 padding: 1.2rem 2rem; }
        .header-content { display: flex; justify-content: space-between; align-items: flex-start;
                          gap: 1rem; }
        .header-actions { display: flex; align-items: center; gap: 0.6rem; flex-shrink: 0; }
        .controls { display: flex; gap: 0.4rem; }
        h1 { font-size: 1.6rem; color: var(--accent); }
        .subtitle { color: var(--subtext); font-size: 0.85rem; margin-top: 0.2rem; }
        .header-facts { display: flex; flex-wrap: wrap; gap: 0.2rem 1.2rem; margin-top: 0.6rem;
                        font-size: 0.82rem; color: var(--subtext); }
        .header-facts strong { color: var(--text); font-weight: 600; }
        main { max-width: 1300px; margin: 0 auto; padding: 1.5rem 2rem 2rem; }
        h2 { font-size: 1.2rem; margin-bottom: 1rem; color: var(--text);
             border-bottom: 1px solid var(--border); padding-bottom: 0.4rem; }
        h3 { font-size: 1rem; margin: 1rem 0 0.5rem; color: var(--subtext); }
        h4 { font-size: 0.9rem; margin: 0.8rem 0 0.4rem; color: var(--subtext); }
        .summary-block { margin-bottom: 1.5rem; }
        .glance-note { color: var(--subtext); font-size: 0.8rem; margin: -0.4rem 0 0.8rem; }
        .glance-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));
                       gap: 0.8rem; }
        .glance-tile { background: var(--card); border: 1px solid var(--border);
                       border-radius: 10px; padding: 0.9rem 1rem; }
        .glance-label { font-size: 0.8rem; color: var(--subtext); }
        .glance-value { font-size: 1.9rem; font-weight: 700; line-height: 1.2; margin: 0.15rem 0; }
        .glance-change { font-size: 0.78rem; }
        .glance-change.better { color: var(--green); }
        .glance-change.worse { color: var(--red); }
        .glance-change.flat, .glance-change.none { color: var(--subtext); }
        .glance-was { margin-left: 0.5rem; color: var(--subtext); }
        .attention-list { list-style: none; }
        .attention-list li { background: var(--card); border: 1px solid var(--border);
                             border-left: 4px solid var(--yellow); border-radius: 6px;
                             padding: 0.5rem 0.8rem; margin-bottom: 0.4rem; font-size: 0.92rem; }
        .attention-list a { color: var(--text); text-decoration: none; }
        .attention-list a:hover { text-decoration: underline; }
        .attention-clear { color: var(--green); font-size: 0.95rem; }
        .group-section { margin-bottom: 0.8rem; }
        details.group { background: var(--card); border: 1px solid var(--border);
                        border-radius: 10px; }
        details.group > summary { cursor: pointer; padding: 0.8rem 1rem; font-size: 1.02rem;
                                  list-style: none; }
        details.group > summary::-webkit-details-marker { display: none; }
        details.group > summary::before { content: "▸"; display: inline-block;
                                          margin-right: 0.6rem; color: var(--subtext); }
        details.group[open] > summary::before { content: "▾"; }
        .grp-title { font-weight: 600; }
        .grp-sum { color: var(--subtext); font-size: 0.9rem; }
        .group-body { padding: 0 1rem 1rem; }
        .block { margin-top: 1rem; overflow-x: auto; }
        .block > h3 { margin-top: 0; }
        .block-note { color: var(--subtext); font-size: 0.85rem; margin-bottom: 0.6rem; }
        .block table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
        details.show-all { margin-top: 0.6rem; }
        details.show-all > summary { cursor: pointer; color: var(--accent); font-size: 0.85rem;
                                     padding: 0.2rem 0; }
        .definitions dt { font-weight: 600; margin-top: 0.6rem; }
        .definitions dd { color: var(--subtext); font-size: 0.9rem; }
        .tiles-row { display: flex; flex-wrap: wrap; gap: 1rem; }
        .tile { background: var(--card); border: 1px solid var(--border); border-radius: 10px;
                padding: 1.2rem 1.5rem; min-width: 140px; text-align: center; }
        .tile.ok { border-color: var(--green); }
        .tile.warn { border-color: var(--yellow); }
        .tile.bad { border-color: var(--red); }
        .tile-value { font-size: 2rem; font-weight: 700; }
        .tile-label { font-size: 0.8rem; color: var(--subtext); margin-top: 0.3rem; }
        table th, table td { padding: 0.6rem 1rem; text-align: left;
                             border-bottom: 1px solid var(--border); }
        table th { background: var(--bg2); font-weight: 600; }
        tr.row-error td { color: #c62828; }
        tr.row-warn td { color: #e65100; }
        [data-theme="dark"] tr.row-error td { color: #ff6b6b; }
        [data-theme="dark"] tr.row-warn td { color: #ffd166; }
        .count-cards { display: flex; flex-wrap: wrap; gap: 1rem; }
        .count-card { background: var(--card); border: 1px solid var(--border); border-radius: 10px;
                      padding: 1rem 1.5rem; min-width: 160px; text-align: center; }
        .count-value { font-size: 1.8rem; font-weight: 700; color: var(--accent); }
        .count-label { font-size: 0.8rem; color: var(--subtext); margin-top: 0.25rem; }
        .theme-toggle, .ctl { background: none; border: 1px solid var(--border);
                              border-radius: 6px; padding: 0.4rem 0.8rem; color: var(--text);
                              cursor: pointer; }
        .ctl { font-size: 0.75rem; padding: 0.25rem 0.6rem; }
        footer { text-align: center; padding: 2rem; font-size: 0.8rem; color: var(--subtext); }
        footer a { color: var(--accent); }
        .history-svg { display: block; width: 100%; max-width: 620px; height: auto;
                       overflow: visible; }
        .compliance-hero {
          padding: 1.8rem 2rem; border-radius: 12px; margin-bottom: 1rem;
          text-align: center; border: 2px solid transparent;
        }
        .compliance-hero-green { background: #e8f5e9; border-color: var(--green); }
        .compliance-hero-amber { background: #fff3e0; border-color: var(--yellow); }
        .compliance-hero-red   { background: #ffebee; border-color: var(--red); }
        [data-theme="dark"] .compliance-hero-green { background: #1b3a1e; }
        [data-theme="dark"] .compliance-hero-amber { background: #3e2a00; }
        [data-theme="dark"] .compliance-hero-red   { background: #3b0d0d; }
        .compliance-hero-value { font-size: 3.5rem; font-weight: 800; color: var(--text); }
        .compliance-hero-label { font-size: 1rem; color: var(--subtext); margin-top: 0.4rem; }
        .empty-note { color: var(--subtext); font-size: 0.85rem; font-style: italic;
                      margin-top: 0.4rem; }
        .device-link { color: inherit; text-decoration: underline dotted; }
        .device-anchor { display: block; visibility: hidden; height: 0; }
        :target { background: rgba(255,234,0,0.18); transition: background 0.4s ease; }
        .skip-link {
          position: absolute;
          top: -999px;
          left: 0;
          background: #004165;
          color: #fff;
          padding: 8px 16px;
          border-radius: 0 0 6px 0;
          font-size: 0.85rem;
          font-weight: 600;
          z-index: 9999;
          text-decoration: none;
        }
        .skip-link:focus { top: 0; }
        \(HtmlSectionFormatters.additionalCSS)
        @media (prefers-reduced-motion: reduce) {
          :target { transition: none; }
        }
        /* Print: light colours, no controls, and every group open (the script opens them
           before printing; the PDF export renders them open). */
        @media print {
          :root, [data-theme="dark"] {
            --bg: #ffffff !important;
            --bg2: #ffffff !important;
            --card: #ffffff !important;
            --text: #000000 !important;
            --subtext: #444 !important;
            --border: #bbb !important;
          }
          body { background: #fff !important; color: #000 !important; }
          header { background: #fff !important; }
          .compliance-hero-green { background: #e8f5e9 !important; }
          .compliance-hero-amber { background: #fff3e0 !important; }
          .compliance-hero-red   { background: #ffebee !important; }
          .theme-toggle, .controls, .skip-link { display: none !important; }
          details.group > summary::before { content: ""; margin: 0; }
          details > summary { page-break-after: avoid; }
          a { color: #000 !important; text-decoration: none; }
        }
        </style>
        """
    }

    // MARK: JavaScript

    func buildScript() -> String {
        """
        <script>
        (function() {
          // Restore persisted theme preference; default is light.
          const saved = localStorage.getItem('jr-theme');
          if (saved === 'dark') {
            document.documentElement.setAttribute('data-theme', 'dark');
          }
        })();
        function toggleTheme() {
          const html = document.documentElement;
          const next = html.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
          html.setAttribute('data-theme', next);
          localStorage.setItem('jr-theme', next);
          const btn = document.querySelector('.theme-toggle');
          if (btn) btn.setAttribute('aria-pressed', next === 'dark' ? 'true' : 'false');
        }
        // Expand all / Collapse all.
        document.addEventListener('click', function(e) {
          var ctl = e.target.closest('[data-action]');
          if (!ctl) { return; }
          var open = ctl.getAttribute('data-action') === 'expand';
          document.querySelectorAll('details').forEach(function(d) { d.open = open; });
        });
        // A link to something inside a closed group opens the groups around it first.
        document.addEventListener('click', function(e) {
          var link = e.target.closest('a[href^="#"]');
          if (!link) { return; }
          jrReveal(decodeURIComponent(link.getAttribute('href').slice(1)));
        });
        function jrReveal(id) {
          var target = document.getElementById(id);
          if (!target) { return; }
          if (target.tagName === 'DETAILS') { target.open = true; }
          for (var n = target.parentElement; n; n = n.parentElement) {
            if (n.tagName === 'DETAILS') { n.open = true; }
          }
        }
        window.addEventListener('load', function() {
          if (location.hash.length > 1) {
            jrReveal(decodeURIComponent(location.hash.slice(1)));
          }
        });
        // Printing shows everything: open every group, then put back what was closed.
        var jrOpenedForPrint = [];
        window.addEventListener('beforeprint', function() {
          jrOpenedForPrint = [];
          document.querySelectorAll('details:not([open])').forEach(function(d) {
            d.open = true;
            jrOpenedForPrint.push(d);
          });
        });
        window.addEventListener('afterprint', function() {
          jrOpenedForPrint.forEach(function(d) { d.open = false; });
          jrOpenedForPrint = [];
        });
        // Cleanup Analysis tab navigation.
        // Buttons have class="cleanup-tab" and data-target="cpane-<id>".
        // Panes have id="cpane-<id>" and class="cleanup-pane [active]".
        document.addEventListener('click', function(e) {
          var btn = e.target.closest('.cleanup-tab');
          if (!btn) return;
          var container = btn.closest('.cleanup-tabs');
          if (!container) return;
          // Deactivate all sibling tabs.
          container.querySelectorAll('.cleanup-tab').forEach(function(t) {
            t.classList.remove('active');
            t.setAttribute('aria-selected', 'false');
            t.setAttribute('tabindex', '-1');
          });
          // Activate the clicked tab.
          btn.classList.add('active');
          btn.setAttribute('aria-selected', 'true');
          btn.setAttribute('tabindex', '0');
          // Deactivate all panes in the same block, then activate the target.
          var block = btn.closest('.block');
          if (block) {
            block.querySelectorAll('.cleanup-pane').forEach(function(p) {
              p.classList.remove('active');
            });
            var target = document.getElementById(btn.getAttribute('data-target'));
            if (target) target.classList.add('active');
          }
        });
        </script>
        """
    }
}
