import ArgumentParser
import Foundation
import XCTest
@testable import JamfReports

/// `jamf-reports scaffold` — `--csv` is optional (2.6): omitting it writes a
/// minimal jamf-cli-only config via the same `ScaffoldService.writeMinimalConfig`
/// the GUI's "Skip for now" onboarding path uses, so a pure-CLI shop has a
/// headless way to create `config.yaml` at all. Providing `--csv` is unchanged.
final class CLIScaffoldTests: XCTestCase {

    /// NOT `FileManager.temporaryDirectory`: /var/folders resolves under
    /// /private/var, which `CLIRun.requireSafeOutput`'s sensitive-path guard
    /// (correctly) refuses — scaffold writes must target an ordinary user path.
    private func tempDir() throws -> URL {
        let dir = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".jrc-scaffold-test-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    // MARK: - Omitting --csv writes a minimal, loadable config

    func testScaffoldWithoutCSVWritesMinimalConfig() async throws {
        let dir = try tempDir()
        defer { try? FileManager.default.removeItem(at: dir) }
        let outURL = dir.appendingPathComponent("config.yaml")

        let cmd = try Scaffold.parse(["--out", outURL.path])
        XCTAssertNil(cmd.csv, "--csv must be optional")
        try await cmd.run()

        XCTAssertTrue(FileManager.default.fileExists(atPath: outURL.path))
        // Must be the same shape ScaffoldService.writeMinimalConfig produces —
        // and, critically, must actually decode as a valid ReportConfig.
        let written = try String(contentsOf: outURL, encoding: .utf8)
        XCTAssertTrue(written.contains("minimal workspace config"))
        XCTAssertNoThrow(try ConfigLoader.load(from: outURL))
    }

    // MARK: - Providing --csv is unchanged (regression)

    func testScaffoldWithCSVBehaviorUnchanged() async throws {
        let dir = try tempDir()
        defer { try? FileManager.default.removeItem(at: dir) }
        let csvURL = dir.appendingPathComponent("export.csv")
        try "Computer Name,Serial Number,Operating System Version\n"
            .write(to: csvURL, atomically: true, encoding: .utf8)
        let outURL = dir.appendingPathComponent("config.yaml")

        let cmd = try Scaffold.parse(["--csv", csvURL.path, "--out", outURL.path])
        XCTAssertEqual(cmd.csv, csvURL.path)
        try await cmd.run()

        let written = try String(contentsOf: outURL, encoding: .utf8)
        XCTAssertTrue(written.contains("computer_name: \"Computer Name\""),
                      "CSV-driven scaffold must still map detected columns")
        XCTAssertTrue(written.contains("generated by Jamf Reports scaffold"))
        XCTAssertNoThrow(try ConfigLoader.load(from: outURL))
    }

    // MARK: - Existing-file overwrite semantics are identical on both paths

    func testScaffoldWithoutCSVOverwritesExistingFile() async throws {
        let dir = try tempDir()
        defer { try? FileManager.default.removeItem(at: dir) }
        let outURL = dir.appendingPathComponent("config.yaml")
        try "stale: true\n".write(to: outURL, atomically: true, encoding: .utf8)

        let cmd = try Scaffold.parse(["--out", outURL.path])
        try await cmd.run()

        let written = try String(contentsOf: outURL, encoding: .utf8)
        XCTAssertFalse(written.contains("stale: true"),
                       "scaffold is an initial-setup command and must overwrite --out")
        XCTAssertTrue(written.contains("minimal workspace config"))
    }

    func testScaffoldWithCSVOverwritesExistingFile() async throws {
        let dir = try tempDir()
        defer { try? FileManager.default.removeItem(at: dir) }
        let csvURL = dir.appendingPathComponent("export.csv")
        try "Computer Name\n".write(to: csvURL, atomically: true, encoding: .utf8)
        let outURL = dir.appendingPathComponent("config.yaml")
        try "stale: true\n".write(to: outURL, atomically: true, encoding: .utf8)

        let cmd = try Scaffold.parse(["--csv", csvURL.path, "--out", outURL.path])
        try await cmd.run()

        let written = try String(contentsOf: outURL, encoding: .utf8)
        XCTAssertFalse(written.contains("stale: true"),
                       "scaffold is an initial-setup command and must overwrite --out")
        XCTAssertTrue(written.contains("generated by Jamf Reports scaffold"))
    }
}
